packages:
  - block
  - model
  - software
  - test
  - ui
  - workflow

catalog:
  "@platforma-sdk/model": 1.79.14
  "@platforma-sdk/ui-vue": 1.79.14
  "@platforma-sdk/workflow-tengo": 6.6.3
  "@platforma-sdk/block-tools": 2.11.0
  "@platforma-sdk/test": 1.79.14
  "@platforma-sdk/tengo-builder": 4.0.8
  "@platforma-sdk/package-builder": 3.13.0
  '@milaboratories/multi-sequence-alignment': 1.46.3
  "@platforma-sdk/blocks-deps-updater": 2.0.0

  "@milaboratories/graph-maker": 1.2.10
  "@milaboratories/helpers": 1.14.2
  '@platforma-open/milaboratories.runenv-r-tcr-disco': 1.0.0
  '@platforma-open/milaboratories.runenv-r-differential-expression': 1.0.7
  "@platforma-open/milaboratories.runenv-python-3": 1.4.9

  "vue": 3.5.24

  "typescript": ~5.6.3
  "turbo": 2.5.4
  "vitest": ~2.1.9

  "@changesets/cli": 2.29.5
  "@milaboratories/ts-builder": 1.5.2
  "@milaboratories/ts-configs": 1.2.3
  shx: ~0.4.0
